(define (main)
  (let ((polar-number (make-from-mag-ang 5 10)))
    (println (polar-number 'real-part))
    (println (polar-number 'imag-part))
    (println (polar-number 'magnitude))
    (println (polar-number 'angle))))

(define (make-from-mag-ang m a)
  (define (dispatch op)
    (cond ((eq? op 'real-part) (* m (cos a)))
          ((eq? op 'imag-part) (* m (sin a)))
          ((eq? op 'magnitude) m)
          ((eq? op 'angle) a)
          (else (error "Unknown op -- MAKE-FROM-MAG-ANG" op))))
  dispatch)
